# ==============================================================================
# File: app/jobs/content_jobs.py
# Purpose: Task functions for weekly social media content generation.
#
#          Public entry point (called by weekly_content_job.py via job_manager):
#
#            generate_weekly_content_for_business(ctx)
#              Generates 3 platform-specific social media posts for the week:
#                - Instagram caption with hashtags
#                - WhatsApp status with CTA
#                - Google Business post (professional + SEO-aware)
#
#          Pipeline steps:
#            1. Load business profile — skip if inactive, deleted, or no
#               WhatsApp number configured
#            2. Check daily report rate limit (content shares the
#               reports_generated quota — it is a generated AI output)
#            3. Gather review context from the last 14 days:
#               - Average star rating
#               - Dominant sentiment (most common label)
#            4. Build special_context from business_description if present
#            5. Call content_generation_service.generate_weekly_content()
#               — returns ContentGenerationResult or ContentGenerationError
#            6. Deliver all content pieces via WhatsApp using
#               whatsapp_service.send_report() (multi-part delivery)
#            7. Track usage — increment content_pieces_generated by the
#               number of pieces in the result (typically 3)
#
#          Rate limiting:
#            Content generation shares the reports_generated daily quota.
#            This is intentional — both are expensive AI generation tasks.
#            If the quota is exhausted (e.g. a weekly + monthly report
#            both ran today), content generation is skipped until tomorrow.
#
#          Context gathering window:
#            14 days of reviews are used for sentiment and rating context.
#            This gives a richer signal than the current week alone, especially
#            for businesses with low review volume.
#
#          Failure handling:
#            - ContentGenerationError → log, mark failed, return
#            - WhatsApp delivery failure → log warning, still track usage
#              (content was generated — quota was consumed)
#            - Any unhandled exception → captured by failsafe in job_manager
#
#          Multi-tenancy:
#            All repository queries are scoped by business_id.
#            No cross-business data access occurs in this file.
# ==============================================================================

import logging
from datetime import date, datetime, timedelta, timezone
from typing import Optional

from app.config.constants import ReviewSentiment, ServiceName
from app.database.models.business_model import BusinessModel
from app.jobs.job_manager import JobContext, JobResult, make_result
from app.services.content_generation_service import (
    ContentGenerationError,
    ContentGenerationResult,
)
from app.utils.rate_limiter import check_report_limit
from app.utils.usage_tracker import track_content_generated

logger = logging.getLogger(ServiceName.SCHEDULER)

# Rolling window for review context used in content generation
_CONTEXT_WINDOW_DAYS: int = 14

# Max chars from business_description used as special_context in prompt
_MAX_SPECIAL_CONTEXT_CHARS: int = 200


# ==============================================================================
# Public entry point — called by weekly_content_job.py via job_manager
# ==============================================================================

async def generate_weekly_content_for_business(ctx: JobContext) -> JobResult:
    """
    Generate and deliver the weekly social media content pack for one business.

    Produces 3 platform-specific posts (Instagram, WhatsApp status, Google
    Business post) and delivers them to the business owner via WhatsApp.

    Content is generated by content_generation_service using OpenAI with a
    template fallback. Context is drawn from the last 14 days of review data.

    Called by weekly_content_job.py via run_job_for_business().

    Args:
        ctx: JobContext from job_manager with db session and all services.

    Returns:
        JobResult. Never raises.
    """
    result = make_result("weekly_content", str(ctx.business_id))
    log_extra = {
        "service": ServiceName.SCHEDULER,
        "job": "weekly_content",
        "business_id": str(ctx.business_id),
    }

    # ------------------------------------------------------------------
    # Step 1: Load and validate business
    # ------------------------------------------------------------------
    business = await _load_business(ctx, log_extra)
    if business is None:
        result.skipped += 1
        return result

    # ------------------------------------------------------------------
    # Step 2: Rate limit check
    # Content shares the reports_generated daily quota
    # ------------------------------------------------------------------
    quota = await check_report_limit(ctx.db, ctx.business_id)
    if not quota.allowed:
        logger.info(
            "Content job skipped — daily report/content limit reached",
            extra={
                **log_extra,
                "used": quota.current_count,
                "limit": quota.limit,
            },
        )
        result.skipped += 1
        return result

    # ------------------------------------------------------------------
    # Step 3: Gather review context from the last 14 days
    # ------------------------------------------------------------------
    avg_rating, dominant_sentiment = await _gather_review_context(
        ctx, log_extra
    )

    # ------------------------------------------------------------------
    # Step 4: Build special_context from business_description
    # ------------------------------------------------------------------
    special_context = _extract_special_context(business)

    # ------------------------------------------------------------------
    # Step 5: Generate content
    # ------------------------------------------------------------------
    logger.info(
        "Generating weekly content",
        extra={
            **log_extra,
            "business_name": business.business_name,
            "avg_rating": avg_rating,
            "dominant_sentiment": dominant_sentiment,
            "has_special_context": bool(special_context),
        },
    )

    content = await ctx.content_service.generate_weekly_content(
        business_id=str(ctx.business_id),
        business_name=business.business_name,
        business_type=business.business_type or "Local Business",
        avg_rating=avg_rating,
        dominant_sentiment=dominant_sentiment,
        special_context=special_context,
    )

    # ------------------------------------------------------------------
    # Handle generation failure
    # ------------------------------------------------------------------
    if isinstance(content, ContentGenerationError):
        logger.error(
            "Weekly content generation failed",
            extra={
                **log_extra,
                "reason": content.reason,
                "detail": content.detail,
            },
        )
        result.success = False
        result.add_error(
            f"Content generation failed: {content.reason} — {content.detail}"
        )
        return result

    # ------------------------------------------------------------------
    # Step 6: Deliver via WhatsApp (multi-part)
    # ------------------------------------------------------------------
    messages = content.to_whatsapp_messages()

    delivery = await ctx.whatsapp_service.send_report(
        db=ctx.db,
        business_id=str(ctx.business_id),
        report_parts=messages,
        report_type="weekly_content",
    )

    if delivery.success:
        logger.info(
            "Weekly content delivered",
            extra={
                **log_extra,
                "pieces": len(content.pieces),
                "week_label": content.week_label,
                "used_fallback": content.used_fallback,
                "business_name": business.business_name,
            },
        )
    else:
        logger.warning(
            "Weekly content WhatsApp delivery failed",
            extra={
                **log_extra,
                "error": delivery.error,
                "pieces_generated": len(content.pieces),
            },
        )

    # ------------------------------------------------------------------
    # Step 7: Usage tracking
    # Track the number of pieces generated (typically 3 per cycle).
    # Always tracked regardless of delivery outcome — content was built
    # and the OpenAI quota was consumed.
    # ------------------------------------------------------------------
    try:
        await track_content_generated(
            ctx.db,
            ctx.business_id,
            count=len(content.pieces),
        )
    except Exception as exc:
        # Non-fatal — never abort for tracking failure
        logger.warning(
            "Failed to track content_pieces_generated",
            extra={**log_extra, "error": str(exc)},
        )

    result.processed += 1
    return result


# ==============================================================================
# Internal helpers
# ==============================================================================

async def _load_business(
    ctx: JobContext,
    log_extra: dict,
) -> Optional[BusinessModel]:
    """
    Load and validate the business profile.

    Skips businesses that are not found, inactive, deleted, or missing
    a WhatsApp number. Businesses without Google integration are still
    eligible — content does not require Google reviews to run (context
    gathering will simply return defaults).

    Args:
        ctx:       JobContext with db and business_repo.
        log_extra: Structured log context dict.

    Returns:
        BusinessModel if valid and active, else None.
    """
    business = await ctx.business_repo.get_by_id(ctx.db, ctx.business_id)

    if not business:
        logger.warning(
            "Content job skipped — business not found",
            extra=log_extra,
        )
        return None

    if not business.is_active or business.is_deleted:
        logger.info(
            "Content job skipped — business inactive or deleted",
            extra={**log_extra, "business_name": business.business_name},
        )
        return None

    if not business.owner_whatsapp_number:
        logger.info(
            "Content job skipped — no WhatsApp number configured",
            extra={**log_extra, "business_name": business.business_name},
        )
        return None

    return business


async def _gather_review_context(
    ctx: JobContext,
    log_extra: dict,
) -> tuple[float, str]:
    """
    Gather avg_rating and dominant_sentiment from the last 14 days of reviews.

    Both values are used as context for the content generation prompt.
    Defaults to (4.0, "positive") if no reviews exist or queries fail —
    a neutral positive signal that produces safe, encouraging content.

    Args:
        ctx:       JobContext with db and review_repo.
        log_extra: Structured log context dict.

    Returns:
        tuple[float, str]: (avg_rating, dominant_sentiment).
        avg_rating is 1.0–5.0. dominant_sentiment is "positive",
        "negative", or "neutral".
    """
    since_dt = datetime.now(timezone.utc) - timedelta(days=_CONTEXT_WINDOW_DAYS)

    # Default fallback values
    avg_rating: float = 4.0
    dominant_sentiment: str = ReviewSentiment.POSITIVE

    # Average rating
    try:
        fetched_avg = await ctx.review_repo.get_average_rating_since(
            ctx.db,
            business_id=ctx.business_id,
            since=since_dt,
        )
        if fetched_avg is not None:
            avg_rating = float(fetched_avg)
    except Exception as exc:
        logger.debug(
            "Failed to fetch avg rating for content context — using default",
            extra={**log_extra, "error": str(exc)},
        )

    # Dominant sentiment — pick the most common sentiment label
    try:
        sentiment_counts = await ctx.review_repo.count_by_sentiment_since(
            ctx.db,
            business_id=ctx.business_id,
            since=since_dt,
        )
        dominant_sentiment = _dominant_sentiment_from_counts(sentiment_counts)
    except Exception as exc:
        logger.debug(
            "Failed to fetch sentiment counts for content context — using default",
            extra={**log_extra, "error": str(exc)},
        )

    return avg_rating, dominant_sentiment


def _dominant_sentiment_from_counts(counts: dict[str, int]) -> str:
    """
    Determine the dominant sentiment label from a sentiment count dict.

    The dict has keys "positive", "negative", "neutral" with int counts.
    Returns the label with the highest count. Ties are broken by priority:
    positive > neutral > negative (to err on the side of optimistic content).

    Args:
        counts: Dict from review_repo.count_by_sentiment_since().

    Returns:
        str: "positive", "negative", or "neutral".
    """
    if not counts or all(v == 0 for v in counts.values()):
        return ReviewSentiment.POSITIVE

    # Priority order for tie-breaking
    priority = [
        ReviewSentiment.POSITIVE,
        ReviewSentiment.NEUTRAL,
        ReviewSentiment.NEGATIVE,
    ]

    # Find max count, then apply priority for tie-breaking
    max_count = max(counts.values())
    for label in priority:
        if counts.get(label, 0) == max_count:
            return label

    return ReviewSentiment.POSITIVE


def _extract_special_context(business: BusinessModel) -> Optional[str]:
    """
    Extract a special context string from the business description field.

    The business_description column stores optional context the owner
    registered during onboarding — e.g. "We now offer home delivery" or
    "New branch opening in December". This is injected into the content
    generation prompt to make posts timely and specific.

    Truncated to _MAX_SPECIAL_CONTEXT_CHARS to keep the prompt size
    within the token budget.

    Args:
        business: BusinessModel instance.

    Returns:
        str if business_description is non-empty, else None.
    """
    if not business.business_description:
        return None

    description = business.business_description.strip()
    if not description:
        return None

    if len(description) > _MAX_SPECIAL_CONTEXT_CHARS:
        return description[:_MAX_SPECIAL_CONTEXT_CHARS]

    return description